/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Secret": {
    get: {
      parameters: {
        query: {
          Id?: parameters["rowFilter.Secret.Id"];
          KeyId?: parameters["rowFilter.Secret.KeyId"];
          Secret?: parameters["rowFilter.Secret.Secret"];
          Salt?: parameters["rowFilter.Secret.Salt"];
          AesIv?: parameters["rowFilter.Secret.AesIv"];
          CreatedAt?: parameters["rowFilter.Secret.CreatedAt"];
          ExpiresAt?: parameters["rowFilter.Secret.ExpiresAt"];
          SearchKey?: parameters["rowFilter.Secret.SearchKey"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Secret"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Secret */
          Secret?: definitions["Secret"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          Id?: parameters["rowFilter.Secret.Id"];
          KeyId?: parameters["rowFilter.Secret.KeyId"];
          Secret?: parameters["rowFilter.Secret.Secret"];
          Salt?: parameters["rowFilter.Secret.Salt"];
          AesIv?: parameters["rowFilter.Secret.AesIv"];
          CreatedAt?: parameters["rowFilter.Secret.CreatedAt"];
          ExpiresAt?: parameters["rowFilter.Secret.ExpiresAt"];
          SearchKey?: parameters["rowFilter.Secret.SearchKey"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          Id?: parameters["rowFilter.Secret.Id"];
          KeyId?: parameters["rowFilter.Secret.KeyId"];
          Secret?: parameters["rowFilter.Secret.Secret"];
          Salt?: parameters["rowFilter.Secret.Salt"];
          AesIv?: parameters["rowFilter.Secret.AesIv"];
          CreatedAt?: parameters["rowFilter.Secret.CreatedAt"];
          ExpiresAt?: parameters["rowFilter.Secret.ExpiresAt"];
          SearchKey?: parameters["rowFilter.Secret.SearchKey"];
        };
        body: {
          /** Secret */
          Secret?: definitions["Secret"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Secret: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    Id: string;
    KeyId: string;
    Secret: string;
    Salt: string;
    AesIv: string;
    CreatedAt: string;
    ExpiresAt: string;
    SearchKey?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** Secret */
  "body.Secret": definitions["Secret"];
  "rowFilter.Secret.Id": string;
  "rowFilter.Secret.KeyId": string;
  "rowFilter.Secret.Secret": string;
  "rowFilter.Secret.Salt": string;
  "rowFilter.Secret.AesIv": string;
  "rowFilter.Secret.CreatedAt": string;
  "rowFilter.Secret.ExpiresAt": string;
  "rowFilter.Secret.SearchKey": string;
}

export interface operations {}

export interface external {}
